spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db_name
    username: your_db_user
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver   # <-- Este es el driver correcto para MySQL

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
